from datetime import timedelta
from feast import Entity, Field, FeatureView, FileSource, ValueType
from feast.types import Float32, Float64, Int64, String, Bool

# 1. Define the Source (Point to your processed Parquet file)
# CHANGE 'path' to the absolute path of your parquet file
credit_stats_source = FileSource(
    name="credit_stats_source",
    path="C:\\Kuslu\\project\\Credit Scoring with XAI\\Data\\Processed\\application_train_processed.parquet",
    timestamp_field="event_timestamp", # You might need to add a dummy timestamp column if none exists
    created_timestamp_column="created",
)

# 2. Define the Entity (The ID we use to look up a user)
applicant = Entity(name="applicant", join_keys=["SK_ID_CURR"], value_type=ValueType.INT64)

# 3. Define the Feature View (The actual columns)
credit_risk_view = FeatureView(
    name="credit_risk_features",
    entities=[applicant],
    ttl=timedelta(days=3650), # How old can the data be? (10 years)
            schema=[Field(name='SK_ID_CURR', dtype=Int64),
Field(name='TARGET', dtype=Int64),
Field(name='CODE_GENDER', dtype=String),
Field(name='FLAG_OWN_CAR', dtype=Int64),
Field(name='FLAG_OWN_REALTY', dtype=Int64),
Field(name='CNT_CHILDREN', dtype=Int64),
Field(name='AMT_INCOME_TOTAL', dtype=Float64),
Field(name='AMT_CREDIT', dtype=Float64),
Field(name='AMT_ANNUITY', dtype=Float64),
Field(name='AMT_GOODS_PRICE', dtype=Float64),
Field(name='NAME_TYPE_SUITE', dtype=String),
Field(name='NAME_EDUCATION_TYPE', dtype=String),
Field(name='NAME_FAMILY_STATUS', dtype=String),
Field(name='NAME_HOUSING_TYPE', dtype=String),
Field(name='REGION_POPULATION_RELATIVE', dtype=Float64),
Field(name='DAYS_REGISTRATION', dtype=Float64),
Field(name='DAYS_ID_PUBLISH', dtype=Float64),
Field(name='OWN_CAR_AGE', dtype=Float64),
Field(name='FLAG_MOBIL', dtype=Int64),
Field(name='FLAG_EMP_PHONE', dtype=Int64),
Field(name='FLAG_WORK_PHONE', dtype=Int64),
Field(name='FLAG_CONT_MOBILE', dtype=Int64),
Field(name='FLAG_PHONE', dtype=Int64),
Field(name='FLAG_EMAIL', dtype=Int64),
Field(name='CNT_FAM_MEMBERS', dtype=Float64),
Field(name='REGION_RATING_CLIENT', dtype=Int64),
Field(name='REGION_RATING_CLIENT_W_CITY', dtype=Int64),
Field(name='WEEKDAY_APPR_PROCESS_START', dtype=String),
Field(name='HOUR_APPR_PROCESS_START', dtype=Int64),
Field(name='REG_REGION_NOT_LIVE_REGION', dtype=Int64),
Field(name='REG_REGION_NOT_WORK_REGION', dtype=Int64),
Field(name='LIVE_REGION_NOT_WORK_REGION', dtype=Int64),
Field(name='REG_CITY_NOT_LIVE_CITY', dtype=Int64),
Field(name='REG_CITY_NOT_WORK_CITY', dtype=Int64),
Field(name='LIVE_CITY_NOT_WORK_CITY', dtype=Int64),
Field(name='ORGANIZATION_TYPE', dtype=String),
Field(name='EXT_SOURCE_1', dtype=Float64),
Field(name='EXT_SOURCE_2', dtype=Float64),
Field(name='EXT_SOURCE_3', dtype=Float64),
Field(name='APARTMENTS_AVG', dtype=Float64),
Field(name='BASEMENTAREA_AVG', dtype=Float64),
Field(name='YEARS_BEGINEXPLUATATION_AVG', dtype=Float64),
Field(name='YEARS_BUILD_AVG', dtype=Float64),
Field(name='COMMONAREA_AVG', dtype=Float64),
Field(name='ELEVATORS_AVG', dtype=Float64),
Field(name='ENTRANCES_AVG', dtype=Float64),
Field(name='FLOORSMAX_AVG', dtype=Float64),
Field(name='FLOORSMIN_AVG', dtype=Float64),
Field(name='LANDAREA_AVG', dtype=Float64),
Field(name='LIVINGAPARTMENTS_AVG', dtype=Float64),
Field(name='LIVINGAREA_AVG', dtype=Float64),
Field(name='NONLIVINGAPARTMENTS_AVG', dtype=Float64),
Field(name='NONLIVINGAREA_AVG', dtype=Float64),
Field(name='APARTMENTS_MODE', dtype=Float64),
Field(name='BASEMENTAREA_MODE', dtype=Float64),
Field(name='YEARS_BEGINEXPLUATATION_MODE', dtype=Float64),
Field(name='YEARS_BUILD_MODE', dtype=Float64),
Field(name='COMMONAREA_MODE', dtype=Float64),
Field(name='ELEVATORS_MODE', dtype=Float64),
Field(name='ENTRANCES_MODE', dtype=Float64),
Field(name='FLOORSMAX_MODE', dtype=Float64),
Field(name='FLOORSMIN_MODE', dtype=Float64),
Field(name='LANDAREA_MODE', dtype=Float64),
Field(name='LIVINGAPARTMENTS_MODE', dtype=Float64),
Field(name='LIVINGAREA_MODE', dtype=Float64),
Field(name='NONLIVINGAPARTMENTS_MODE', dtype=Float64),
Field(name='NONLIVINGAREA_MODE', dtype=Float64),
Field(name='APARTMENTS_MEDI', dtype=Float64),
Field(name='BASEMENTAREA_MEDI', dtype=Float64),
Field(name='YEARS_BEGINEXPLUATATION_MEDI', dtype=Float64),
Field(name='YEARS_BUILD_MEDI', dtype=Float64),
Field(name='COMMONAREA_MEDI', dtype=Float64),
Field(name='ELEVATORS_MEDI', dtype=Float64),
Field(name='ENTRANCES_MEDI', dtype=Float64),
Field(name='FLOORSMAX_MEDI', dtype=Float64),
Field(name='FLOORSMIN_MEDI', dtype=Float64),
Field(name='LANDAREA_MEDI', dtype=Float64),
Field(name='LIVINGAPARTMENTS_MEDI', dtype=Float64),
Field(name='LIVINGAREA_MEDI', dtype=Float64),
Field(name='NONLIVINGAPARTMENTS_MEDI', dtype=Float64),
Field(name='NONLIVINGAREA_MEDI', dtype=Float64),
Field(name='FONDKAPREMONT_MODE', dtype=String),
Field(name='TOTALAREA_MODE', dtype=Float64),
Field(name='EMERGENCYSTATE_MODE', dtype=String),
Field(name='OBS_30_CNT_SOCIAL_CIRCLE', dtype=Float64),
Field(name='DEF_30_CNT_SOCIAL_CIRCLE', dtype=Float64),
Field(name='OBS_60_CNT_SOCIAL_CIRCLE', dtype=Float64),
Field(name='DEF_60_CNT_SOCIAL_CIRCLE', dtype=Float64),
Field(name='DAYS_LAST_PHONE_CHANGE', dtype=Float64),
Field(name='FLAG_DOCUMENT_2', dtype=Int64),
Field(name='FLAG_DOCUMENT_3', dtype=Int64),
Field(name='FLAG_DOCUMENT_4', dtype=Int64),
Field(name='FLAG_DOCUMENT_5', dtype=Int64),
Field(name='FLAG_DOCUMENT_6', dtype=Int64),
Field(name='FLAG_DOCUMENT_7', dtype=Int64),
Field(name='FLAG_DOCUMENT_8', dtype=Int64),
Field(name='FLAG_DOCUMENT_9', dtype=Int64),
Field(name='FLAG_DOCUMENT_10', dtype=Int64),
Field(name='FLAG_DOCUMENT_11', dtype=Int64),
Field(name='FLAG_DOCUMENT_12', dtype=Int64),
Field(name='FLAG_DOCUMENT_13', dtype=Int64),
Field(name='FLAG_DOCUMENT_14', dtype=Int64),
Field(name='FLAG_DOCUMENT_15', dtype=Int64),
Field(name='FLAG_DOCUMENT_16', dtype=Int64),
Field(name='FLAG_DOCUMENT_17', dtype=Int64),
Field(name='FLAG_DOCUMENT_18', dtype=Int64),
Field(name='FLAG_DOCUMENT_19', dtype=Int64),
Field(name='FLAG_DOCUMENT_20', dtype=Int64),
Field(name='FLAG_DOCUMENT_21', dtype=Int64),
Field(name='AMT_REQ_CREDIT_BUREAU_HOUR', dtype= Float64),
Field(name='AMT_REQ_CREDIT_BUREAU_DAY', dtype=Float64),
Field(name='AMT_REQ_CREDIT_BUREAU_WEEK', dtype=Float64),
Field(name='AMT_REQ_CREDIT_BUREAU_MON', dtype=Float64),
Field(name='AMT_REQ_CREDIT_BUREAU_QRT', dtype=Float64),
Field(name='AMT_REQ_CREDIT_BUREAU_YEAR', dtype=Float64),
Field(name='AMT_ANNUITY_is_null', dtype=Int64),
Field(name='AMT_GOODS_PRICE_is_null', dtype=Int64),
Field(name='OWN_CAR_AGE_is_null', dtype=Int64),
Field(name='CNT_FAM_MEMBERS_is_null', dtype=Int64),
Field(name='EXT_SOURCE_1_is_null', dtype=Int64),
Field(name='EXT_SOURCE_2_is_null', dtype=Int64),
Field(name='EXT_SOURCE_3_is_null', dtype=Int64),
Field(name='APARTMENTS_AVG_is_null', dtype=Int64),
Field(name='BASEMENTAREA_AVG_is_null', dtype=Int64),
Field(name='YEARS_BEGINEXPLUATATION_AVG_is_null', dtype=Int64),
Field(name='YEARS_BUILD_AVG_is_null', dtype=Int64),
Field(name='COMMONAREA_AVG_is_null', dtype=Int64),
Field(name='ELEVATORS_AVG_is_null', dtype=Int64),
Field(name='ENTRANCES_AVG_is_null', dtype=Int64),
Field(name='FLOORSMAX_AVG_is_null', dtype=Int64),
Field(name='FLOORSMIN_AVG_is_null', dtype=Int64),
Field(name='LANDAREA_AVG_is_null', dtype=Int64),
Field(name='LIVINGAPARTMENTS_AVG_is_null', dtype=Int64),
Field(name='LIVINGAREA_AVG_is_null', dtype=Int64),
Field(name='NONLIVINGAPARTMENTS_AVG_is_null', dtype=Int64),
Field(name='NONLIVINGAREA_AVG_is_null', dtype=Int64),
Field(name='APARTMENTS_MODE_is_null', dtype=Int64),
Field(name='BASEMENTAREA_MODE_is_null', dtype=Int64),
Field(name='YEARS_BEGINEXPLUATATION_MODE_is_null', dtype=Int64),
Field(name='YEARS_BUILD_MODE_is_null', dtype=Int64),
Field(name='COMMONAREA_MODE_is_null', dtype=Int64),
Field(name='ELEVATORS_MODE_is_null', dtype=Int64),
Field(name='ENTRANCES_MODE_is_null', dtype=Int64),
Field(name='FLOORSMAX_MODE_is_null', dtype=Int64),
Field(name='FLOORSMIN_MODE_is_null', dtype=Int64),
Field(name='LANDAREA_MODE_is_null', dtype=Int64),
Field(name='LIVINGAPARTMENTS_MODE_is_null', dtype=Int64),
Field(name='LIVINGAREA_MODE_is_null', dtype=Int64),
Field(name='NONLIVINGAPARTMENTS_MODE_is_null', dtype=Int64),
Field(name='NONLIVINGAREA_MODE_is_null', dtype=Int64),
Field(name='APARTMENTS_MEDI_is_null', dtype=Int64),
Field(name='BASEMENTAREA_MEDI_is_null', dtype=Int64),
Field(name='YEARS_BEGINEXPLUATATION_MEDI_is_null', dtype=Int64),
Field(name='YEARS_BUILD_MEDI_is_null', dtype=Int64),
Field(name='COMMONAREA_MEDI_is_null', dtype=Int64),
Field(name='ELEVATORS_MEDI_is_null', dtype=Int64),
Field(name='ENTRANCES_MEDI_is_null', dtype=Int64),
Field(name='FLOORSMAX_MEDI_is_null', dtype=Int64),
Field(name='FLOORSMIN_MEDI_is_null', dtype=Int64),
Field(name='LANDAREA_MEDI_is_null', dtype=Int64),
Field(name='LIVINGAPARTMENTS_MEDI_is_null', dtype=Int64),
Field(name='LIVINGAREA_MEDI_is_null', dtype=Int64),
Field(name='NONLIVINGAPARTMENTS_MEDI_is_null', dtype=Int64),
Field(name='NONLIVINGAREA_MEDI_is_null', dtype=Int64),
Field(name='TOTALAREA_MODE_is_null', dtype=Int64),
Field(name='OBS_30_CNT_SOCIAL_CIRCLE_is_null', dtype=Int64),
Field(name='DEF_30_CNT_SOCIAL_CIRCLE_is_null', dtype=Int64),
Field(name='OBS_60_CNT_SOCIAL_CIRCLE_is_null', dtype=Int64),
Field(name='DEF_60_CNT_SOCIAL_CIRCLE_is_null', dtype=Int64),
Field(name='DAYS_LAST_PHONE_CHANGE_is_null', dtype=Int64),
Field(name='AMT_REQ_CREDIT_BUREAU_HOUR_is_null', dtype=Int64),
Field(name='AMT_REQ_CREDIT_BUREAU_DAY_is_null', dtype=Int64),
Field(name='AMT_REQ_CREDIT_BUREAU_WEEK_is_null', dtype=Int64),
Field(name='AMT_REQ_CREDIT_BUREAU_MON_is_null', dtype=Int64),
Field(name='AMT_REQ_CREDIT_BUREAU_QRT_is_null', dtype=Int64),
Field(name='AMT_REQ_CREDIT_BUREAU_YEAR_is_null', dtype=Int64),
Field(name='AGE_YEAR', dtype=Float64),
Field(name='YEARS_EMPLOYED', dtype=Float64),
Field(name='NAME_INCOME_TYPE_Pensioner', dtype=Bool),
Field(name='NAME_INCOME_TYPE_Rare', dtype=Bool),
Field(name='NAME_INCOME_TYPE_State servant', dtype=Bool),
Field(name='NAME_INCOME_TYPE_Working', dtype=Bool),
Field(name='OCCUPATION_TYPE_Core staff', dtype=Bool),
Field(name='OCCUPATION_TYPE_Drivers', dtype=Bool),
Field(name='OCCUPATION_TYPE_High skill tech staff', dtype=Bool),
Field(name='OCCUPATION_TYPE_Laborers', dtype=Bool),
Field(name='OCCUPATION_TYPE_Managers', dtype=Bool),
Field(name='OCCUPATION_TYPE_Medicine staff', dtype=Bool),
Field(name='OCCUPATION_TYPE_Rare', dtype=Bool),
Field(name='OCCUPATION_TYPE_Sales staff', dtype=Bool),
Field(name='OCCUPATION_TYPE_Security staff', dtype=Bool),
Field(name='OCCUPATION_TYPE_Unknown', dtype=Bool),
Field(name='HOUSETYPE_MODE_Unknown', dtype=Bool),
Field(name='HOUSETYPE_MODE_block of flats', dtype=Bool),
Field(name='WALLSMATERIAL_MODE_Panel', dtype=Bool),
Field(name='WALLSMATERIAL_MODE_Rare', dtype=Bool),
Field(name='WALLSMATERIAL_MODE_Stone_ brick', dtype=Bool),
Field(name='WALLSMATERIAL_MODE_Unknown', dtype=Bool),
Field(name='NAME_CONTRACT_TYPE_Revolving loans', dtype=Bool),],
    source=credit_stats_source,
    online=True,
)
